" Jake's vimrc

" Vundle copy & paste
"""""""""""""""""""""""""""""""""""""""""""""""""""""
set nocompatible              " be iMproved, required
filetype off                  " required

let mapleader = ","
noremap \ ,

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'tpope/vim-fugitive'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'airblade/vim-gitgutter'
Plugin 'vim-airline/vim-airline'
Plugin 'w0rp/ale'
Plugin 'fatih/vim-go'
Plugin 'vim-scripts/tComment'
Plugin 'kchmck/vim-coffee-script'
Plugin 'leafgarland/typescript-vim'
Plugin 'thoughtbot/vim-rspec'
Plugin 'hashivim/vim-terraform'

" Style
Plugin 'arcticicestudio/nord-vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"""""""""""""""""""""""""""""""""""""""""""""""""""""

syntax enable          " Turn on syntax highlighting.
colorscheme nord
set backspace=2        " Normal backspaces.
set tabstop=2          " Global tab width.
set expandtab          " Use spaces instead of tabs.
set number
"set cursorline         " Love this, but dramatically slows vim down... :cry:
set nowrap
set listchars=trail:·,eol:¬ "tab:▸\ ,eol:¬,space:·,trail:·
set ignorecase
set smartcase
set shiftwidth=2
set showcmd
set clipboard=unnamed  " Use system clipboard
set term=screen-256color

" Navigation Settings
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-W>

" Editing VIM
nnoremap <leader>ev :vsplit $MYVIMRC<CR>
nnoremap <leader>sv :source $MYVIMRC<CR>
nnoremap <leader>D yyp
nnoremap <leader>\ :NERDTreeToggle<CR>
nnoremap <leader>zt 4kzt4j
nnoremap <leader>zb 4jzb4k
"nnoremap <leader>| :NERDTreeFind<CR>
" Custom controls

" Move a line one line down
map - ddp
map _ ddkP
" Delete a line faster
inoremap <c-d> <esc>ddi
" Uppercase the current word
inoremap <c-u> <esc>viwUea
nnoremap <c-u> viwU
" CtrlP settings
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|\.git\|tmp\|packages\|vendor'
  "asdf
" GitGutter settings
set signcolumn=yes

" Ale settings
let g:ale_lint_on_text_changed = 'never'
let g:ale_set_highlights = 0

" Airline Settings
" let g:airline#extensions#tmuxline#enabled = 0
let g:airline_section_z = '%#__accent_bold#%{g:airline_symbols.linenr}%4l%#__restore__#:%3v'
" set statusline=%<%f\                     " Filename
" set statusline+=%w%h%m%r                 " Options
" set statusline+=\[%{&ff}/%Y]             " Filetype
" set statusline+=\ [%{getcwd()}]

" Vim Config
let g:go_highlight_build_constraints = 1
let g:go_highlight_types = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_fmt_command = "goimports"
let g:go_auto_sameids = 1

" TF
let g:terraform_align=1
let g:terraform_fmt_on_save=1
" Go Tests - Need to set this up for only *.go files
nnoremap <leader>t :GoTest<CR>
nnoremap <leader>v :GoVet<CR>
